name: OSS

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.AccessKey_ID }}
          access-key-secret: ${{ secrets.Access_Key_Secret }}
      - run: |
          find . -type f \( \
          -name "README.md" -o \
          -name ".gitignore" -o \
          -name "package.json" -o \
          -name "theme.json" -o \
          -name "index.js" \
          \) -prune -o \
          -type d \( \
            -name ".git" -o \
            -name ".github" -o \
            -name "utils" -o \
            -name "ossutil_output" \
          \) -prune -o \
          -type f -print | \
          ossutil cp -rf - oss://jx3box/logo/
