name: OSS

on:
  push:
    branches:
      - master # 只在master上push触发部署
    paths-ignore: # 下列文件的变更不触发部署，可以自行添加
      - README.md
      - LICENSE

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{secrets.AccessKey_ID}}
          access-key-secret: ${{secrets.Access_Key_Secret}}
      - run: ossutil cp -rf logo oss://jx3box/logo/
      - run: ossutil cp -rf logo-dark oss://jx3box/logo-dark/
      - run: ossutil cp -rf logo-light oss://jx3box/logo-light/
      - run: ossutil cp -rf logo-golden oss://jx3box/logo-golden/