name: OSS

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.AccessKey_ID }}
          access-key-secret: ${{ secrets.Access_Key_Secret }}
      - run: |
          ossutil cp -rf . oss://jx3box/logo/ \
            --exclude "README.md" \
            --exclude "LICENSE" \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude ".gitignore" \
            --exclude ".vscode/" \
            --exclude "utils/" \
            --exclude "node_modules/" \
            --exclude "package-lock.json" \
            --exclude "package.json" \、
            --exclude "theme.json" \
            --exclude "index.js" \
            --exclude "ossutil_output/"
