name: OSS

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.AccessKey_ID }}
          access-key-secret: ${{ secrets.Access_Key_Secret }}
      - run: |
          mkdir -p temp_sync
          cp -r . temp_sync/
          
          # 删除不需要的文件和文件夹
          rm -rf temp_sync/.git \temp_sync/.github \
                temp_sync/utils \
                temp_sync/ossutil_output \
                temp_sync/README.md \
                temp_sync/.gitignore \
                temp_sync/package.json \
                temp_sync/theme.json \
                temp_sync/index.js
          
          ossutil sync temp_sync/ oss://jx3box/logo/
          # 清理临时目录
          rm -rf temp_sync
