name: OSS

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{ secrets.AccessKey_ID }}
          access-key-secret: ${{ secrets.Access_Key_Secret }}
      - run: ossutil cp -rf logo oss://jx3box/logo/logo/
      - run: ossutil cp -rf logo-dark oss://jx3box/logo/logo-dark/
      - run: ossutil cp -rf logo-light oss://jx3box/logo/logo-light/
      - run: ossutil cp -rf logo-golden oss://jx3box/logo/logo-golden/
      - run: ossutil cp -rf app.json oss://jx3box/logo/
